#!/bin/bash

#SBATCH -A $project_name
#SBATCH -J "HiPACE++"
#SBATCH -o hipace-%j.out
#SBATCH -t 00:30:00
#SBATCH --partition=$partition_name
#SBATCH --mem=$memory
#SBATCH --nodes=$num_nodes
#SBATCH --ntasks-per-node=$num_tasks_per_node
#SBATCH --gpus-per-node=$num_tasks_per_node

export MPICH_GPU_SUPPORT_ENABLED=1
export FI_MR_CACHE_MONITOR=memhooks  # alternative cache monitor
export ROCFFT_RTC_CACHE_PATH=/dev/null
export OMP_NUM_THREADS=1

cat << EOF > select_gpu
#!/bin/bash

export ROCR_VISIBLE_DEVICES=\$$SLURM_LOCALID
exec \$$*
EOF

chmod +x ./select_gpu

CPU_BIND="map_cpu:49,57,17,25,1,9,33,41"

#Don't touch the next line, it is used by the
# local runner to find the input filename
# filename_input "$filename_input"

srun --cpu-bind=$${CPU_BIND} ./select_gpu $hipace_binary_path $filename_input
rm -rf ./select_gpu
